openapi: 3.0.0
info:
  title: Todo App Backend API - Phase II
  version: 1.0.0
  description: API for managing user tasks, including creation, retrieval, updates, and deletion.
    All endpoints require JWT authentication and enforce task ownership.

servers:
  - url: /api/{user_id}
    variables:
      user_id:
        default: 'current_user'
        description: The ID of the authenticated user.

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the task.
          readOnly: true
        user_id:
          type: string
          description: ID of the user who owns the task.
          readOnly: true
        title:
          type: string
          description: Brief summary of the task.
          minLength: 1
          maxLength: 200
        description:
          type: string
          nullable: true
          description: Detailed explanation of the task.
          maxLength: 1000
        completed:
          type: boolean
          description: Status of the task (true if completed, false if pending).
          default: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created.
          readOnly: true
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated.
          readOnly: true
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          nullable: true
          maxLength: 1000
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          nullable: true
          maxLength: 1000
    ErrorResponse:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
paths:
  /tasks:
    get:
      summary: List all tasks for the user
      operationId: listTasks
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [completed, pending, all]
          description: Filter tasks by completion status. Defaults to 'all'.
          required: false
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [created_at, updated_at, title]
          description: Sort tasks by a specific field. Defaults to 'created_at'.
          required: false
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
          description: Order of sorting. Defaults to 'asc'.
          required: false
      responses:
        '200':
          description: A list of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input for task creation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: The ID of the task to retrieve or modify.
    get:
      summary: Get details of a specific task
      operationId: getTaskById
      responses:
        '200':
          description: Details of the requested task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: Task not found or not owned by the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update a task
      operationId: updateTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input for task update.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: Task not found or not owned by the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a task
      operationId: deleteTask
      responses:
        '204':
          description: Task deleted successfully.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: Task not found or not owned by the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tasks/{id}/complete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: The ID of the task to toggle completion.
    patch:
      summary: Toggle task completion status
      operationId: toggleTaskCompletion
      responses:
        '200':
          description: Task completion status updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          description: Task not found or not owned by the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ForbiddenError:
      description: You do not have the necessary permissions for the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
